[package]
name = "celery"
version = "0.1.0"
authors = ["epwalsh <epwalsh10@gmail.com>"]
edition = "2018"
keywords = ["celery", "amqp", "rabbitmq", "background-jobs"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/epwalsh/rusty-celery"
homepage = "https://github.com/epwalsh/rusty-celery"
description = "Rust implementation of Celery"

[lib]
name = "celery"
path = "src/lib.rs"

[dependencies]
tokio = { version = "0.2", features = ["full"]}
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
failure = "0.1"
async-trait = "0.1"
lapin = { path = "../lapin", features = ["default", "futures"] }
log = "0.4"
env_logger = "0.7"
futures-util = "0.3"
