[package]
name = "celery"
version = "0.1.0"
authors = ["epwalsh <epwalsh10@gmail.com>"]
edition = "2018"
keywords = ["celery", "amqp", "rabbitmq", "background-jobs"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/epwalsh/rusty-celery"
homepage = "https://github.com/epwalsh/rusty-celery"
description = "Rust implementation of Celery"

[lib]
name = "celery"
path = "src/lib.rs"

[[bin]]
name = "celeryrs"
path = "src/main.rs"
doc = false

[dependencies]
tokio = { version = "0.2", features = ["full"]}
